#!/usr/bin/env python3
"""Render README.md from profile.yaml.

    python3 scripts/render_readme.py

The page is a positioning statement and one card per public repository. Both live in
profile.yaml, and this turns them into markdown, for one reason: adding a repository has
to be adding a row, not rewriting a page. A layout that has to be re-laid out every time
the estate grows is a layout that stops being maintained, and the cards then drift from
what the repositories actually contain.

What a card is allowed to say is constrained by what can be checked. Every card names a
binding: a command, a gate identifier, or a committed artifact, each with the path in the
target repository that has to exist for the claim to mean anything. tests/ resolves every
one of them against the live repository, so a card that outruns its repository fails.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "profile.yaml"
TARGET = ROOT / "README.md"
OWNER = "malex4hire"

BANNER = (
    "<!-- GENERATED from profile.yaml by scripts/render_readme.py. Do not edit this file;\n"
    "     edit profile.yaml. Every claim below is resolved against its repository by tests/. -->\n"
)

# What each kind of binding is called on the page. A card names at least one.
KIND_LABEL = {
    "command": "run",
    "gate": "gate",
    "artifact": "artifact",
}


def profile() -> dict:
    if not SOURCE.is_file():
        raise SystemExit(f"{SOURCE.name} is missing; it is the page's source")
    doc = yaml.safe_load(SOURCE.read_text(encoding="utf-8")) or {}
    for key in ("name", "positioning", "cards"):
        if key not in doc:
            raise SystemExit(f"{SOURCE.name} declares no '{key}'")
    return doc


def card_markdown(name: str, card: dict) -> str:
    url = f"https://github.com/{OWNER}/{name}"
    out = [f"### [{name}]({url})", ""]
    if card.get("line"):
        out += [f"**{card['line'].strip()}**", ""]
    out += [card["proves"].strip(), "", "| | what it is | where it lives |", "|---|---|---|"]
    for binding in card["bindings"]:
        path = binding["path"]
        out.append(
            f"| {KIND_LABEL[binding['kind']]} | `{binding['value']}` | "
            f"[{path}]({url}/blob/main/{path}) |"
        )
    out.append("")
    return "\n".join(out)


def render() -> str:
    doc = profile()
    positioning = [str(line).strip() for line in doc["positioning"] if str(line).strip()]
    if len(positioning) > 3:
        raise SystemExit(
            f"positioning is {len(positioning)} lines; three is the ceiling. A reader who "
            "needs four lines of preamble has already left"
        )

    # One paragraph per line, so three statements read as three and not as a block.
    parts = [f"## {doc['name'].strip()}", ""]
    for line in positioning:
        parts += [line, ""]
    parts += ["---", ""]
    for name, card in doc["cards"].items():
        parts.append(card_markdown(name, card))
    if doc.get("footer"):
        parts += ["---", "", doc["footer"].strip(), ""]

    body = "\n".join(parts)
    return BANNER + "\n" + body.rstrip() + "\n"


def main() -> int:
    rendered = render()
    changed = not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != rendered
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"README.md {'rendered' if changed else 'unchanged'} from profile.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
